package games.platform.crud.gui;

import games.platform.models.Publisher;
import games.platform.utils.DbGlobal;

public class PublisherForm extends javax.swing.JInternalFrame {

    private final String basePublisherIdText = "ID da Editora: ";
    private final Publisher publisher;
    private final boolean newPublisher;

    public PublisherForm(Publisher publisher, boolean newPublisher) {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.publisher = publisher;
        this.newPublisher = newPublisher;

        initComponents();
        populateFields();
    }

    private void populateFields() {
        if (!newPublisher) {
            publisherIdLabel.setText(basePublisherIdText + publisher.getId());
            updateButton.setText("Atualizar");
        } else {
            updateButton.setText("Inserir");
        }
        publisherNameField.setText(publisher.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        publisherIdLabel = new javax.swing.JLabel();
        publisherNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        nameErrorLabel = new javax.swing.JLabel();
        responseLabel = new javax.swing.JLabel();

        setBorder(null);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(850, 509));

        jLabel1.setText("Nome da Editora");

        updateButton.setText("Atualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        nameErrorLabel.setForeground(new java.awt.Color(229, 57, 53));

        responseLabel.setForeground(new java.awt.Color(56, 142, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(responseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(publisherIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(publisherNameField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(publisherIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateButton)
                    .addComponent(responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        nameErrorLabel.setText("");

        String newName = publisherNameField.getText();

        if (newName.length() > 50) {
            nameErrorLabel.setText("Caracteres máximos 50.");
            return;
        } else if (newName.length() < 1) {
            nameErrorLabel.setText("Caracteres mínimos 1.");
            return;
        }

        publisher.setName(newName);
        String response;
        if (newPublisher) {
            response = games.platform.crud.models.Publisher.createPublisher(publisher, DbGlobal.getDb().getConnection());
        } else {
            response = games.platform.crud.models.Publisher.updatePublisher(publisher, DbGlobal.getDb().getConnection());
        }
        responseLabel.setText(response);
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameErrorLabel;
    private javax.swing.JLabel publisherIdLabel;
    private javax.swing.JTextField publisherNameField;
    private javax.swing.JLabel responseLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
